# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build on feature/* branch.

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["feature/*"]
  pull_request:
    branches: ["feature/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: v0.145.0
    steps:
      - name: Checkout project source with submodule
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install go task CLI
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "$HOME/bin" && echo "$HOME/bin" >> "$GITHUB_PATH"
      - name: Install hugo CLI
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_linux-amd64.deb && sudo apt-get install -y ./hugo_extended_0.145.0_linux-amd64.deb
      - name: Launch Hugo build by go-task
        run: task -v dev:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

